name: React CI/CD Testing
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out our code repository (clone our project)
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies 
        run: npm ci
      - name: Print debug info
        run: |
          echo "Node Version: $(node --version)"
          echo "NPM Version: $(npm --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of node_modules: $(ls -l node_modules)"
          
